### PR TITLE
fix: remove debugging line

### PR DESCRIPTION
**Pull request by Lemmmy**
Hi there, this looks like a brilliant project and I can't wait to use it 😄 

When trying to build, I noticed that the build log was being spammed with huge strings and objects (assumingly, the entire AST and source code at every build step), which resulted in create-react-app/craco eventually running out of memory (if my terminal didn't crash before it) and the build failing to complete. I tracked this down to a debugging line that seems to have been left over by #9. This PR removes that line. 

If the line was meant to be left in, then feel free to close this :) 

Thanks for your awesome work!

### CODE REVIEW

**Comment by lukasluecke** [comment]
Yeah noticed the same, pretty sure this should be removed.

**Comment by Lemmmy** [comment]
@lukasluecke If you need a temporary quick fix for your debugging purposes, I have a published patched version at https://www.npmjs.com/package/@lemmmy/babel-plugin-use-what-changed - I won't be maintaining this or anything, especially once this library is patched itself, but it's there if you need it fast :)

**Comment by lukasluecke** [comment]
Thanks, I just patched it locally for now with https://github.com/ds300/patch-package 🙂

**Comment by simbathesailor** [comment]
Hey Thanks for the pull request . Tonight I will release the fix with this pr

**Comment by simbathesailor** [comment]
Released a new version with this fix : https://www.npmjs.com/package/@simbathesailor/babel-plugin-use-what-changed/v/2.0.3. One can install by updating package.json 

```
 "@simbathesailor/babel-plugin-use-what-changed": "^2.0.3",

```

**Pull request merged**
